=== jsabater/calabruix/static/downloads/xml/practica-xml/cataleg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cat="http://exemple.com/cataleg"
           xmlns:joc="http://exemple.com/videojoc"
           targetNamespace="http://exemple.com/cataleg"
           elementFormDefault="qualified">

    <!-- ==================== TIPUS PERSONALITZATS ==================== -->

    <!-- Codi de moneda ISO 4217 (3 lletres majúscules) -->
    <xs:simpleType name="tipusMoneda">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Puntuació de 0 a 100 -->
    <xs:simpleType name="tipusPuntuacio">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Preu (decimal positiu o zero per a jocs gratuïts) -->
    <xs:simpleType name="tipusPreu">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- RAM i disc en GB (enter positiu) -->
    <xs:simpleType name="tipusGB">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- VRAM en MB (enter positiu) -->
    <xs:simpleType name="tipusMB">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Nombre de ressenyes (enter positiu o zero) -->
    <xs:simpleType name="tipusRessenyes">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Plataformes vàlides -->
    <xs:simpleType name="tipusPlataforma">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Windows"/>
            <xs:enumeration value="Mac"/>
            <xs:enumeration value="Linux"/>
            <xs:enumeration value="PlayStation"/>
            <xs:enumeration value="Xbox"/>
            <xs:enumeration value="Switch"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Identificador de videojoc (JOC + 3 dígits) -->
    <xs:simpleType name="tipusIdVideojoc">
        <xs:restriction base="xs:string">
            <xs:pattern value="JOC[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Identificador de DLC (DLC + 3 dígits) -->
    <xs:simpleType name="tipusIdDLC">
        <xs:restriction base="xs:string">
            <xs:pattern value="DLC[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Identificador de recurs -->
    <xs:simpleType name="tipusIdRecurs">
        <xs:restriction base="xs:string">
            <xs:pattern value="img-[a-z0-9\-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Tipus per a text amb idioma -->
    <xs:complexType name="tipusTextIdioma">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- ELEMENT ARREL -->

    <xs:element name="cataleg">
        <xs:complexType>
            <xs:sequence>
                <!-- Metadades del catàleg -->
                <xs:element name="info">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titol" type="xs:string"/>
                            <xs:element name="autor" type="xs:string"/>
                            <xs:element name="actualitzat" type="xs:date"/>
                            <xs:element name="descripcio" type="cat:tipusTextIdioma" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Recursos externs -->
                <xs:element name="recursos" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="recurs" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="cat:tipusIdRecurs" use="required"/>
                                    <xs:attribute name="href" type="xs:anyURI" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute ref="xml:base"/>
                    </xs:complexType>
                </xs:element>

                <!-- Videojocs -->
                <xs:element name="videojocs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="joc:videojoc" minOccurs="15" maxOccurs="20"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="xml:lang"/>
        </xs:complexType>
    </xs:element>

    <!-- VIDEOJOC (namespace joc:) -->

    <xs:element name="videojoc" xmlns="http://exemple.com/videojoc">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titol" type="xs:string"/>
                <xs:element name="descripcio" type="cat:tipusTextIdioma" maxOccurs="unbounded"/>
                <xs:element name="desenvolupador" type="xs:string"/>
                <xs:element name="distribuidor" type="xs:string"/>
                <xs:element name="dataLlancament" type="xs:date"/>
                <xs:element name="generes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genere" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="plataformes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plataforma" type="cat:tipusPlataforma" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="preu">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="cat:tipusPreu">
                                <xs:attribute name="moneda" type="cat:tipusMoneda" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="valoracions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="puntuacio" type="cat:tipusPuntuacio"/>
                            <xs:element name="numRessenyes" type="cat:tipusRessenyes"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="requisits">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="so" type="xs:string"/>
                            <xs:element name="cpu" type="xs:string"/>
                            <xs:element name="ram" type="cat:tipusGB"/>
                            <xs:element name="vram" type="cat:tipusMB"/>
                            <xs:element name="disc" type="cat:tipusGB"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="etiquetes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="etiqueta" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dlcs" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dlc" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="cat:tipusIdDLC" use="required"/>
                                    <xs:attribute name="gratuit" type="xs:boolean" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="cat:tipusIdVideojoc" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jsabater/calabruix/static/xml/practica-xml/cataleg.xml
<?xml version="1.0" encoding="UTF-8"?>
<cat:cataleg xmlns:cat="http://exemple.com/cataleg"
             xmlns:joc="http://exemple.com/videojoc"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://exemple.com/cataleg cataleg.xsd"
             xml:lang="ca">
    
    <!-- Metadades del catàleg -->
    <cat:info>
        <cat:titol>El meu catàleg de videojocs</cat:titol>
        <cat:autor>Nom Alumne</cat:autor>
        <cat:actualitzat>2025-01-15</cat:actualitzat>
        <cat:descripcio xml:lang="ca">Col·lecció personal de videojocs.</cat:descripcio>
        <cat:descripcio xml:lang="en">Personal videogame collection.</cat:descripcio>
    </cat:info>
    
    <!-- Recursos externs amb URI base -->
    <cat:recursos xml:base="https://cdn.exemple.com/imatges/">
        <cat:recurs id="img-portal2" href="portal2.jpg"/>
        <cat:recurs id="img-minecraft" href="minecraft.jpg"/>
    </cat:recursos>
    
    <!-- Videojocs -->
    <cat:videojocs>
        <joc:videojoc id="JOC001">
            <joc:titol>Portal 2</joc:titol>
            <joc:descripcio xml:lang="ca">Joc de trencaclosques en primera persona amb portals.</joc:descripcio>
            <joc:descripcio xml:lang="en">First-person puzzle game with portals.</joc:descripcio>
            <joc:desenvolupador>Valve Corporation</joc:desenvolupador>
            <joc:distribuidor>Valve Corporation</joc:distribuidor>
            <joc:dataLlancament>2011-04-19</joc:dataLlancament>
            <joc:generes>
                <joc:genere>Trencaclosques</joc:genere>
                <joc:genere>Primera persona</joc:genere>
            </joc:generes>
            <joc:plataformes>
                <joc:plataforma>Windows</joc:plataforma>
                <joc:plataforma>Mac</joc:plataforma>
                <joc:plataforma>Linux</joc:plataforma>
            </joc:plataformes>
            <joc:preu moneda="EUR">9.99</joc:preu>
            <joc:valoracions>
                <joc:puntuacio>95</joc:puntuacio>
                <joc:numRessenyes>342567</joc:numRessenyes>
            </joc:valoracions>
            <joc:requisits>
                <joc:so>Windows 7</joc:so>
                <joc:cpu>3.0 GHz P4</joc:cpu>
                <joc:ram>2</joc:ram>
                <joc:vram>512</joc:vram>
                <joc:disc>8</joc:disc>
            </joc:requisits>
            <joc:etiquetes>
                <joc:etiqueta>cooperatiu</joc:etiqueta>
                <joc:etiqueta>un-jugador</joc:etiqueta>
            </joc:etiquetes>
            <joc:dlcs>
                <joc:dlc id="DLC001" gratuit="true">
                    <joc:nom>Peer Review</joc:nom>
                </joc:dlc>
            </joc:dlcs>
        </joc:videojoc>
        <!-- 14-19 videojocs més -->
    </cat:videojocs>
</cat:cataleg>
